### ISSUE TITLE
The J2CL maven plugin expects projects to have excluded dependencies.

### ISSUE THREAD

**Issue by treblereel** [gitgabrio/j2clmavenplugin#1]
During the classPath process, plugin is removing excluded dependencies which are described in pom.xml. This is an expected behaviour and is OK. But the plugin expects every project to have such excluded dependencies, otherwise it returns empty classPath which leads to inability
 to compile the project itself. The fix is simple : check if  'List<Artifact> toRemove' is empty and return unmodified classPath from this method.

**Comment by treblereel** [comment]
[dominodo-j2cl.zip](https://github.com/gitgabrio/j2clmavenplugin/files/2999680/dominodo-j2cl.zip)

**Comment by niloc132** [comment]
I'm not full understanding you here yet, but I will point out that the plugin is in a bit of a state of flux right now - the classpath building mechanism right now assumes (I believe) that all source dirs share the same classpath, even across modules, and this will be changed soon.
