### ISSUE TITLE
Unable to run or build project which use apt generators

### ISSUE THREAD

**Issue by treblereel** [gitgabrio/j2clmavenplugin#3]
During the compile routine the J2CL maven plugin copies generated sources. from generated-sources/annotated to target/{hash} folder which leads to inability to compile because of "duplicate class" error. I suggest to exclude classes from  generated-sources/annotated during compilation, so they ll be compiled only once.

**Comment by niloc132** [comment]
To be clear, the j2cl plugin is not copying the contents of target/generated-sources/annotated at all, but re-running the same annotation processors instead.

One (temporary) solution could be that when running dev mode, tell maven-compiler-plugin to disable running those processors. 

A more long-term solution could be to reuse either the settings of maven-compiler-plugin, or actually invoke the plugin directly as part of dev mode.
